### ISSUE TITLE
UI Issue

### ISSUE THREAD

**Issue by AcidOP** [SpandyBoss/Span41n#8]
To be completely honest with you the UI looks a bit dull. And it will be visually appealing if you center aligned everything.
Can I create a new fork and maybe update some elements?

**Comment by AcidOP** [comment]
Also curious why are you not using the latest version of Nextjs with `app` directory?

**Comment by SpandanSehgal** [comment]
> To be completely honest with you the UI looks a bit dull. And it will be visually appealing if you center aligned everything.
> Can I create a new fork and maybe update some elements?

Hi @AcidOP 
Thanks for your suggestion.
Yes you can create your own fork of the repo.

**Comment by SpandanSehgal** [comment]
> Also curious why are you not using the latest version of Nextjs with `app` directory?

Yea, I know there is new version of Next.js out already, but as I was building this in earlier version so I didn't upgrade to the latest one, also I am not much familiar with the new `app` directory.

But thanks for your honest thoughts 🙂
